config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index, :show] do
    collection do
      get 'search'
      get 'suggest'
    end
  end
  resources :groups, only: [:index, :new, :create, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end
end

app/models/any_information.rb
class AnyInformation < ApplicationRecord
  belongs_to :information
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :users
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :members
  has_many :users, through: :members
end

app/models/information.rb
class Information < ApplicationRecord
  has_many :any_informations
  has_many :users, through: :any_informations
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many    :messages
  has_many    :contacts
  has_many    :members
  has_many    :groups, through: :members
  has_many    :any_informations
  has_many    :informations, through: :any_informations
  belongs_to  :category
  #フォロー申請のアソシエーションと処理の定義
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

# フォローしているかしていないか調べる処理
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

# フォローをする処理
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

# フォローを解除する処理
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 常にログインを要求する
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :team_name, :category_id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @users = User.order('id ASC').limit(20)
  end

  def show
    @category = Category.find(params[:id])
    @users = User.all
  end

  def search
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path, notice: 'グループを削除しました'
  end

  private
  def group_params
    params.require(:group).permit(:group_name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group, only:[:index, :create]
  before_action :set_messages, only:[:index, :create]

  def index
    @user = current_user
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to group_messages_path(params[:group_id])
    else
      render :index, notice: 'メッセージを入力してください'
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    selected_group = Group.find(params[:group_id])
    redirect_to group_messages_path(selected_group, message.id), notice: 'メッセージを削除しました'
  end

  private

  def message_params
    params.require(:message).permit(:body, :created_at).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def set_group
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
  end

  def set_messages
    @messages = @group.messages.includes(:user)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to user_path(@user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:index, :edit, :update]

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(users_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def following
    @title = "フォローリスト"
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "フォロワーリスト"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private

  def users_params
    params.require(:user).permit(:name, :email, :image, :team_name, :region, :body, :result)
  end

  def set_user
    @user = User.find(current_user[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/search.html.erb
  <div id="main_cnt_wrapper">
    <div id="yjContentsBody">
      <div class="yjContainer">
        <div id="categories"><span>ユーザー検索</span></div>
        <!-- カテゴリー検索 -->
        <div class="categories-content">
          <div class="parent-content-a">
            <div class="region-content-a">
              <ul>
                <h2 class="font-size">北海道</h2>
                <li><a href="/categories/1", class="region">北海道</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">東北地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/2", class="region">青森県</a></li>
                <li class="region-2"><a href="/categories/3", class="region">岩手県</a></li>
                <li class="region-2"><a href="/categories/4", class="region">宮城県</a></li>
                <li class="region-2"><a href="/categories/5", class="region">秋田県</a></li>
                <li class="region-2"><a href="/categories/6", class="region">山形県</a></li>
                <li class="region-2"><a href="/categories/7", class="region">福島県</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">関東地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/8", class="region">茨城県</a></li>
                <li class="region-2"><a href="/categories/9", class="region">栃木県</a></li>
                <li class="region-2"><a href="/categories/10", class="region">群馬県</a></li>
                <li class="region-2"><a href="/categories/11", class="region">埼玉県</a></li>
                <li class="region-2"><a href="/categories/12", class="region">千葉県</a></li>
                <li class="region-2"><a href="/categories/13", class="region">東京都</a></li>
                <li class="region-2"><a href="/categories/14", class="region">神奈川県</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">北陸・甲信越地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/15", class="region">新潟県</a></li>
                <li class="region-2"><a href="/categories/16", class="region">富山県</a></li>
                <li class="region-2"><a href="/categories/17", class="region">石川県</a></li>
                <li class="region-2"><a href="/categories/18", class="region">福井県</a></li>
                <li class="region-2"><a href="/categories/19", class="region">山梨県</a></li>
                <li class="region-2"><a href="/categories/20", class="region">長野県</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">東海地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/21", class="region">岐阜県</a></li>
                <li class="region-2"><a href="/categories/22", class="region">静岡県</a></li>
                <li class="region-2"><a href="/categories/23", class="region">愛知県</a></li>
                <li class="region-2"><a href="/categories/24", class="region">三重県</a></li>
              </ul>
            </div>
          </div>
          <div class="parent-content-b">
            <div class="region-content-a">
              <h2 class="font-size">近畿地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/25", class="region">滋賀県</a></li>
                <li class="region-2"><a href="/categories/26", class="region">京都府</a></li>
                <li class="region-2"><a href="/categories/27", class="region">大阪府</a></li>
                <li class="region-2"><a href="/categories/28", class="region">兵庫県</a></li>
                <li class="region-2"><a href="/categories/29", class="region">奈良県</a></li>
                <li class="region-2"><a href="/categories/30", class="region">和歌山県</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">中国地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/31", class="region">鳥取県</a></li>
                <li class="region-2"><a href="/categories/32", class="region">島根県</a></li>
                <li class="region-2"><a href="/categories/33", class="region">岡山県</a></li>
                <li class="region-2"><a href="/categories/34", class="region">広島県</a></li>
                <li class="region-2"><a href="/categories/35", class="region">山口県</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">四国地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/36", class="region">徳島県</a></li>
                <li class="region-2"><a href="/categories/37", class="region">香川県</a></li>
                <li class="region-2"><a href="/categories/38", class="region">愛媛県</a></li>
                <li class="region-2"><a href="/categories/39", class="region">高知県</a></li>
              </ul>
            </div>
            <div class="region-content-a">
              <h2 class="font-size">九州地方</h2>
              <ul>
                <li class="region-2"><a href="/categories/40", class="region">福岡県</a></li>
                <li class="region-2"><a href="/categories/41", class="region">佐賀県</a></li>
                <li class="region-2"><a href="/categories/42", class="region">長崎県</a></li>
                <li class="region-2"><a href="/categories/43", class="region">熊本県</a></li>
                <li class="region-2"><a href="/categories/44", class="region">大分県</a></li>
                <li class="region-2"><a href="/categories/45", class="region">宮崎県</a></li>
                <li class="region-2"><a href="/categories/46", class="region">鹿児島県</a></li>
                <li class="region-2"><a href="/categories/47", class="region">沖縄県</a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- インクリメンタルサーチ -->
        <div id="yjMain">
          <article class="section-a">
            <div class="container">
              <header class="header header--section">
                <h2 class="text-middle">
                  <i class="icon-movie color-gray-light"></i>ワードで検索
                </h2>
              </header>
              <%= form_tag('/categories/search', method: :get) do %>
                <input class="search__query" name="keyword" placeholder="ユーザー名で検索" type="text" value="">
                <button class="btn-search" name="検索" type="submit">検索</button>
                </input>
              <% end %>
              <form accept-charset="utf-8" action="/" class="js-search-submit" method="get">
              </form>
            </div>
          </article>
          <article class="section">
            <div class="container">
              <header class="header header--section">
                <h2 class="text-middle" id="text-result">ユーザーリスト</h2>
              </header>
              <ul class="listview js-lazy-load-images">
                <% @users.each do |user| %>
                <li class="user-li">
                  <!-- 飛ぶリンク先を個別になるようにprefixで記述する -->
                  <%= link_to  user_path(user.id), class: "listview__element--right-icon" do %>
                    <div class="profile-image">
                        <% if user.image.present? %>
                          <%= image_tag user.image, class: "image-a"  %>
                        <% else %>
                          <div class="no-profile-image">No Image</div>
                        <% end %>
                      </div>
                    <div class="col6 push6">
                      <h3 class="text-middle text-break">
                        <span class="color-sub" style="width:26em;">ユーザー名：<%= user.name %></span>
                      </h3>
                      <p class="text-xsmall" style="width:26em;">
                        チーム紹介：<%= user.body %>
                      </p>
                    </div>
                  <% end %>
                </li>
                <% end %>
              </ul>
            </div>
          </article>
        </div>
        <div id="yjSub">
        <a href="/">マイページへ戻る</a>

app/views/categories/show.html.erb
<div class="category">
  <hr>
  <div class="title">
    <span class="eng-lang">SEARCH RESULTS</span><br />
    <span class="ja-lang">ユーザー一覧</span>
  </div>
  <hr>
  <%= link_to "ユーザー検索へ戻る", search_categories_path %><br />
  <%= link_to "マイページへ戻る", root_path(current_user[:id]) %>
  <div class="parent-users">
      <!-- ユーザーをそれぞれ個別にする処理 -->
    <% @users.each do |user| %>
      <div class="users-list">
        <!-- category_idが等しいユーザーのみ表示されるようにif分岐で分ける -->
        <% if @category.id == user.category_id %>
          <!-- 飛ぶリンク先を個別になるようにprefixで記述する -->
          <%= link_to  user_path(user.id), class: "listview__element--right-icon" do %>
            <div class="user-list">
              <div class="user-image-box">
                <% if user.image.present? %>
                  <%= image_tag user.image, class: "user-image-a" %>
                <% else %>
                  <div class="no-image-box">No Image</div>
                <% end %>
              </div>
              <div class="introduct-box">
                <div class="user-name-box">
                  ユーザー名：<%= user.name %>
                  チーム名：<%= user.team_name %>
                </div>
                <div class="user-name-box">
                  チーム名：<%= user.team_name %>
                </div>
                <div class="user-product-box">
                  <% if user.body.present? %>
                   <%= user.body %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="category">
  <hr>
  <div class="title">
    <span class="eng-lang">CHAT LIST</span><br />
    <span class="ja-lang">チャット リスト</span>
  </div>
  <hr>
  <%= link_to "新規チャットルームを作成する", new_group_path %><br>
  <%= link_to "マイページへ戻る", root_path(current_user[:id]) %>
  <div class="parent-users">
      <!-- ユーザーをそれぞれ個別にする処理 -->
    <% @groups.each do |group| %>
      <div class="users-list">
        <%= link_to group_messages_path(group.id) do %>
          <div class="user-list">
            <div class="introduct-box">
              <div class="user-name-box">
                チャットルーム名：<%= group.group_name %>
              </div>
            </div>
          </div>
        <% end %>
        <%= link_to "削除", group_path(group.id), method: :delete, class: "delete-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="content">
  <h2>チャットルームの作成</h2>
  <%= form_for @group do |f| %>
    <div class="field">
      <%= f.label "チャットルーム名" %><br />
      <%= f.text_field :group_name, class: "acount_form" %>
    </div>
    <div class="field">
      <%= f.label "ユーザーを選択してください" %><br />
      <!-- 自分も選択しないと表示されない(のちに仕様そのものを改善) -->
      <%= f.label "※ 自分も選択してください" %><br />
      <%= f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b| %>
        <%= b.label {b.check_box + b.text} %>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit "チャットルームを作成", class: "create_acount" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<div class="a-content">
  <div class="left-content">
    <div class="chat-current-user-name">
      <%= @user.name %><br>
      <%= link_to "マイページへ戻る", root_path(current_user[:id]) %>
    </div>
    <div class="chat-current-user-groups">
      <h3>チャットリスト</h3>
      <% @groups.each do |group| %>
        <div class="chat-group-name">
          <%= link_to group_messages_path(group.id) do %>
            <%= group.group_name %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="right-content">
    <div class="min-title">
      <span class="title-c">CHAT ROOM</span><br />
      <%= @group.group_name %><br />
      <div class="members">
        MEMBER: <%= @user.name %>
      </div>
    </div>
    <div class="body-box">
      <% @messages.each do |m| %>
        <div class="text-content">
          <div class="text-user-name">
            <%= m.user.name %>
          </div>
          <div class="text-created">
            <%= m.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
          </div>
          <div class="text-body">
            <%= m.body %>
          </div>
          <%= link_to "削除", group_message_path(m.group.id, m.id), method: :delete, class: "message-delete-button" %>
        </div>
      <% end %>
    </div>
    <div class="chat-footer">
      <%= form_for [@group, @message], html: {id: 'item_form', class: 'message-form'} do |f| %>
        <div class="text-body-form">
          <%= f.text_field :body, placeholder: "メッセージを入力してください" %>
          <%= f.submit "送信", class: "submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.id == user.id %>
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow', user: user %>
  <% else %>
    <%= render 'users/follow', user: user %>
  <% end %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <li class="menu-content" id="follow-follower">
    <a href="<%= following_user_path(@user) %>">
      フォロー
      <strong id="following" class="stat">
        <%= @user.followings.count %>
      </strong>
      人
    </a>
  </li>
  <li class="menu-content" id="follow-follower">
    <a href="<%= followers_user_path(@user) %>">
      フォロワー
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      人
    </a>
  </li>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<div class="account-page">
  <div class="edit-user">
    <%= form_for(current_user) do |f| %>
      <div class="field">
        <p>ユーザーネーム</p>
        <%= f.text_field :name, autofocus: true, class: "acount_form" %>
      </div>

      <div class="field file">
        <%= f.label "プロフィール画像を選択" %>
        <%= f.file_field :image %>
      </div>

      <div class="field">
        <p>チームネーム</p>
        <%= f.text_field :team_name, autofocus: true, class: "acount_form" %>
      </div>

      <div class="field">
        <%= f.select :category_id, [["地域を選択してください", 0], ["北海道", 1], ["青森県", 2], ["岩手県", 3], ["宮城県", 4], ["秋田県", 5], ["山形県", 6], ["福島県", 7], ["茨城県", 8], ["栃木県", 9], ["群馬県", 10], ["埼玉県", 11], ["千葉県", 12], ["東京都", 13], ["神奈川県", 14], ["新潟県", 15], ["富山県", 16], ["石川県", 17], ["福井県", 18], ["山梨県", 19], ["長野県", 20], ["岐阜県", 21], ["静岡県", 22], ["愛知県", 23], ["三重県", 24], ["滋賀県", 25], ["京都府", 26], ["大阪府", 27], ["兵庫県", 28], ["奈良県", 29], ["和歌山県", 30], ["鳥取県", 31], ["島根県", 32], ["岡山県", 33], ["広島県", 34], ["山口県", 35], ["徳島県", 36], ["香川県", 37], ["愛媛県", 38], ["高知県", 39], ["福岡県", 40], ["佐賀県", 41], ["長崎県", 42], ["熊本県", 43], ["大分県", 44], ["宮崎県", 45], ["鹿児島県", 46], ["沖縄県", 47]],{}, class: "select_form" %>
      </div>

      <div class="field">
        <p>メールアドレス</p>
        <%= f.email_field :email, autofocus: true, class: "acount_form" %>
      </div>

      <div class="field">
        <p>チーム紹介</p>
        <%= f.text_area :body, class: "acount_form product-box" %>
      </div>

      <div class="field">
        <p>試合結果</p>
        <%= f.text_area :result, class: "acount_form product-box" %>
      </div>
      <div class="field">
        <%= link_to "マイページへ戻る", root_path(current_user[:id]) %>
        <%= f.submit "変更する", class: "submit"%>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="a-content">
  <div class="left-content">
    <ul class="info-content">
      <li>マイページ</li>
      <li class="menu-content"><a>お知らせ</a></li>
      <li class="menu-content"><%= link_to "チャットリスト", groups_path %></li>
      <h4>
        <%= render 'users/stats' %>
      </h4>
      <li class="menu-content"><%= link_to "ユーザー検索", search_categories_path %></li>
      <li class="menu-content"><%= link_to "プロフィール編集", edit_user_path(@user.id) %></li>
      <li class="menu-content"><a>お問い合わせ</a></li>
      <li class="menu-content"><a>利用規約</a></li>
      <li class="menu-content"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%></li>
    </ul>
  </div>
  <div class="right-content">
    <div class="head-content">
      <div class="p-image-content">
        <% if @user.image.present? %>
          <%= image_tag @user.image, class: "user-image" %>
        <% else %>
          <div class="image-content">No Image</div>
        <% end %>
      </div>
      <div class="content-b">
        ユーザー名：<%= @user.name %>
      </div>
      <div class="content-b">
        チーム名：  <%= @user.team_name %>
      </div>
      <div class="content-b">
        所在地：<%= @user.category.category_name %>
      </div>
    </div>
    <div class="introduct-content">
      <div class="c-content">チーム紹介</div>
      <div class="c-introduct-content">
        <%= @user.body %>
      </div>
    </div>
    <div class="result-content">
      <div class="c-content">試合結果</div>
      <div class="c-introduct-content">
        <%= @user.result %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="a-content">
  <div class="left-content">
    <ul class="info-content">
      <li class="menu-content"><%= link_to "メッセージを送る", new_group_path %></li>
      <% if current_user.id != @user.id %>
        <li class="menu-content">
          <a>
            <span id="user_<%= @user.id %>" class="follow-wrapper">
              <%= render 'follow_form', user: @user if signed_in? %>
            </span>
          </a>
        </li>
      <% end %>
      <h4>
        <%= render 'users/stats' %>
      </h4>
      <li class="menu-content"><%= link_to "ユーザー検索", search_categories_path %></li>
    </ul>
    <%= link_to "マイページへ戻る", root_path(current_user[:id]), class: "link-root" %>
  </div>
  <div class="right-content">
    <div class="head-content">
      <div class="p-image-content">
        <% if @user.image.present? %>
          <%= image_tag @user.image, class: "user-image" %>
        <% else %>
          <div class="image-content">No Image</div>
        <% end %>
      </div>
      <div class="content-b">
        ユーザー名：<%= @user.name %>
      </div>
      <div class="content-b">
        チーム名：  <%= @user.team_name %>
      </div>
      <div class="content-b">
        所在地：<%= @user.category.category_name %>
      </div>
    </div>
    <div class="introduct-content">
      <div class="c-content">チーム紹介</div>
      <div class="c-introduct-content">
        <%= @user.body %>
      </div>
    </div>
    <div class="result-content">
      <div class="c-content">試合結果</div>
      <div class="c-introduct-content">
        <%= @user.result %>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="span4">
    <section>
    <h2 id="follow-title"><%= @title %></h2>
      <% if @users.any? %>
        <% @users.each do |user| %>
        <li class="user-li">
          <!-- 飛ぶリンク先を個別になるようにprefixで記述する -->
          <%= link_to  user_path(user.id), class: "listview__element--right-icon" do %>
            <div class="profile-image">
                <% if user.image.present? %>
                  <%= image_tag user.image, class: "image-a"  %>
                <% else %>
                  <div class="no-profile-image">No Image</div>
                <% end %>
              </div>
            <div class="col6 push6">
              <h3 class="text-middle text-break">
                <span class="color-sub" style="width:26em;">ユーザー名：<%= user.name %></span>
              </h3>
              <p class="text-xsmall" style="width:26em;">
                チーム紹介：<%= user.body %>
              </p>
            </div>
          <% end %>
        </li>
        <% end %>
      <% end %>
    </section>
  </aside>
  <%= link_to "マイページへ戻る", root_path(current_user[:id]), class: "link-root" %>
</div>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
  <table>
  <tr>
    <td>  <%= user.username %> </td>
    <td><%= link_to '詳細', user_path(user) %></td>
  </tr>

  </table>
<% end %>
<%= link_to "マイページへ戻る", root_path(current_user[:id]), class: "link-root" %>